### ISSUE TITLE
Problema com CORS e JWT

### ISSUE THREAD

**Issue by raphapizzi** [rtenorioh/Press-Ticket#141]
Olá!

Estava rodando normalmente aqui já faz alguns meses. Porém ao atualizar ontem eu não consegui fazer mais login.

No log do Back-End eu tenho o seguinte:
`0|Press-Ti | INFO [14:31:21.137] (3247): Session:
0|Press-Ti | ERROR [14:31:29.625] (3247): {"name":"JsonWebTokenError","message":"jwt malformed"}
0|Press-Ti | WARN [14:31:34.765] (3247):
0|Press-Ti |     message: "ERR_SESSION_EXPIRED"
0|Press-Ti |     statusCode: 401
0|Press-Ti | ERROR [14:31:34.871] (3247): {"name":"JsonWebTokenError","message":"jwt malformed"}`

Inspecionando pelo Browser eu vi que esta com algum problema de CORS também:
`Access to XMLHttpRequest at 'https://back-ticket.xxx.com.br/auth/login' from origin 'https://ticket.xxx.com.br' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://ticket.xxx.com.br/' that is not equal to the supplied origin.`

Já tentei fazer de tudo, já gerei o JWT novamente, revi as .env, fiz a build de tudo novamente e agora por último eu deletei tudo e reinstalei e mesmo assim ainda esta com este problema. 

Alguma luz?

**Comment by raphapizzi** [comment]
O problema do CORS eu resolvi, era uma questão do meu Nginx, pois no mesmo ambiente eu tinha outros sites.

Porém depois do último update o Whatsapp fica desconectando várias vezes. No log tem aparecido algumas coisas como:
`ERROR [18:43:30.846] (4135): {"name":"TokenExpiredError","message":"jwt expired","expiredAt":"2024-11-06T18:05:22.000Z"}`

`0|Press-Ticket-backend  | Error: TypeError: Cannot read properties of undefined (reading 'sendMessage')
0|Press-Ticket-backend  |     at /home/deploy/Press-Ticket/backend/dist/services/HubServices/SendTextMessageHubService.js:53:44
0|Press-Ticket-backend  |     at Generator.next (<anonymous>)
0|Press-Ticket-backend  |     at fulfilled (/home/deploy/Press-Ticket/backend/dist/services/HubServices/SendTextMessageHubService.js:5:58)`
