### ISSUE TITLE
/home/Press-Ticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221             throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));

### ISSUE THREAD

**Issue by plvsouza** [rtenorioh/Press-Ticket#54]
Instalação clean estou obtendo esse erro

`Error: Evaluation failed: TypeError: message.getLinks is not a function
    at window.WWebJS.getMessageModel (__puppeteer_evaluation_script__:295:30)
    at __puppeteer_evaluation_script__:20:48
    at Array.map (<anonymous>)
    at __puppeteer_evaluation_script__:20:25
    at ExecutionContext._evaluateInternal (/home/Press-Ticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/Press-Ticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async GroupChat.fetchMessages (/home/Press-Ticket/backend/node_modules/whatsapp-web.js/src/structures/Chat.js:178:24)`

**Comment by plvsouza** [comment]
Atualizando, estou rodando num Ubuntu 20.04 com node v16.18.0

**Comment by pedriin647** [comment]
esse erro é quando vai dar build? tenta deletar a pasta do /node_modules e tentar dar o npm install novamente

**Comment by l4p84** [comment]
Vai no celular e remove as conexões atuais e le o QR Code novamente

**Comment by plvsouza** [comment]
> esse erro é quando vai dar build? tenta deletar a pasta do /node_modules e tentar dar o npm install novamente

O erro ocorre já com a plataforma rodando

**Comment by plvsouza** [comment]
O problema foi resolvido removendo a pasta node_modules e executando o npm install e npm run build.
